#ifndef HELP_H
#define HELP_

#define COMMAND_TAGS "-- [COMMAND TAGS] --\n\n[Note tags]\n  id=<interval>\n  channel=<x/*>\n  trigger=<interval>\n--\n  *id: note id from 0 to 127\n    > optional, default 0:127\n  *channel: value from 0 to 16 for channel, * for any channel\n    > optional, default *\n  *trigger: note velocity from 0 to 127 that triggers the command\n    > optional, default 1:127\n\n[Controller tags]\n  id=<interval>\n  channel=<x/*>\n  range=<interval>\n  remap=<interval>\n  float=<true/false>\n--\n  *id: controller id from 0 to 127\n    > optional, default 0:127\n  *channel: value from 0 to 16 for channel, * for any channel\n    > optional, default *\n  *range: controller value from 0 to 127 that triggers command\n    > optional, default 0:127\n  *remap: remaps the range to given interval\n    > optional, default same as range\n  *float: boolean value defining if output is a floating point value\n    > optional, default false\n\n[Pitch bend tags]\n  range=<interval>\n  remap=<interval>\n  float=<true/false>\n--\n  *range: controller value from -8192 to 8191 that triggers command\n    > optional, default -8192:8191\n  *remap: remaps the range to given interval\n    > optional, default same as range\n  *float: boolean value defining if output is a floating point value\n    > optional, default false\n\n[Interval Format]\n  x:y   range from x to y\n  x     single value x\n  *     all possible values"
#define MIM_FORMAT "-- [MIM FILE FORMAT] --\n\nDevice <name>\n  Command <type>\n    shell=<shell command>\n    <tag>=<value>\n    <tag>=<value>\n    ...\n  Command <type>\n    ...\n\nDevice <name>\n...\n\n--\n*name: string referring to client name of the device\n  > mandatory\n*type: type of the signal: note/controller/pitch/system/connect/disconnect\n  > mandatory\n*shell: shell command to be executed\n  > mandatory\n\nShell commands can be concatenated with \"\" or ''\nComments are written with // or # and end at end of line\nMultiple tags can be put on the same line by separating them with ;\nSee --command-tags for optional command tags"
#define SHELL_FORMAT "-- [SHELL FORMAT] --\n\nShell command follows regular shell format\n\n-- [Environment] --\n\n[Note]\n  $id: id of the note\n  $channel: channel of the note\n  $velocity: velocity of the note\n\n[Controller]\n  $value: value of the controller (remapped)\n  $id: id of the controller\n  $channel: channel of the controller\n  $rawvalue: original value of the controller\n\n[Pitch]\n  $value: value of the bend (remapped)\n  $rawvalue: original value of the bend\n\n[System]\n  $code: hexadecimal code of the system signal"
#define ZFD_FORMAT "-- [ZFD FILE FORMAT] --\n\nZFD format: http://zawz.net/doc/ztd/zfd.html\n\n[<device>,<device>]\n\n-- <device> format --\n  {\n    name=<name>\n    commands=[<command>,<command>]\n  }\n--\n*name: string referring to client name of the device\n\n<command> format\n  {\n    type=<type>\n    shell=<shell command>\n    <tag>=<value>\n    <tag>=<value>\n    ...\n  }\n--\n*type: type of the signal: note/controller/pitch/system/connect/disconnect\n  > mandatory\n*shell: shell command to be executed\n  > mandatory\n\nShell commands can be concatenated with \"\" or ''\nsee --command-tags for optional command tags"

#endif //HELP_H
